name: BUILD_GH_PAGES
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # 拉取代码
    - name: Checkout
      uses: actions/checkout@main

    # 1、生成静态文件
    - name: Build
      run: yarn && yarn build

    # 2、部署到 GitHub Pages
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        # 注意这里的folder: dist 是仓库根目录下的 dist，也就是 npm run build 生成静态资源的路径,也有些是 /public
        folder: dist
        # 构建结果存储的仓库
        repository-name: lx164/vue-color-avatar
        # 构建结果存储的分支
        branch: ghp_vue-color-avatar
        # commit文本内容
        commit-message: ${{github.event.head_commit.message}}